---
title: "Alaska Health Quality"
author: "Iwo Augustyński"
output: ioslides_presentation
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

<!-- ## McKinsey indicators -->

<!-- [Public Health](https://www.usnews.com/news/best-states/rankings/health-care/public-health) (some of) -->

<!-- - Low Infant Mortality Rate -->
<!-- - Low Mortality Rate -->
<!-- - Mental Health (?) -->

<!-- [Health Care Quality](https://www.usnews.com/news/best-states/rankings/health-care/healthcare-quality) -->

<!-- - Fewest Hospital Readmissions -->
<!-- - Medicare Quality -->
<!-- - Nursing Home Quality -->
<!-- - Preventable Admissions -->
# Map of data sources

## Primary Data Sources

- [CMS](https://www.cms.gov/Research-Statistics-Data-and-Systems/Research-Statistics-Data-and-Systems.html) - Centers for Medicare & Medicaid Services
  - [HCAPS](https://www.hcahpsonline.org/) - Hospital Consumer Assessment of Healthcare Providers and Systems based on data submitted by participating hospitals to **CMS** and **AHRQ**
  - [Medicare Compare](https://data.medicare.gov/data/hospital-compare) - (Hospital, Nursing Home, Physician, Home Health, Dialysis Facility, Hospice compare) Official datasets provided by the **CMS**
- [AHRQ](https://www.ahrq.gov) - Agency for Healthcare Research and Quality
- [CDC](http://wonder.cdc.gov) - National Center for Health Statistics


## Suggested Databases

| Source | Resource | Description |
| ------ | -------- | ----------- |
| AHRQ | [NHQR/NHDR Web Site](https://nhqrnet.ahrq.gov/inhqrdr/Alaska/dashboard) | State dashboards and benchmarks, timeseries, only complicated excel files |
| CMS | [data.cms.gov](https://data.cms.gov/) | Easy access (CSV, JSON, API), broad coverage |
| CMS | Medicare Compare | Easy access, quality assessment included. |
| CDC | [data.cdc.gov](https://data.cdc.gov/) | General data (mortality rate, cause of death etc.) |
| KFF | [Henry J. Kaiser Family Foundation](https://www.kff.org/statedata/) | 12 categories, only manual download | 



# Technical Considerations

##

- Retrieval of data - csv file through API, updated annually (by script in job scheluder)
- Presentation of results
  - Flexdashboard: standalone static website; + free, fast, easy to integrate; -- static;
  - Shiny Dashboard: interactive application; + free, flexible;   -- slower, requires shiny server;
  - Tableau: interactive dashboard; + easier to amend changes; -- requires expensive licence;


# Issues to discuss

## 

- Role of ownership
- Small number of reporting hospitals (Safety of Care, Medical Imaging)
- Small number of hospitals - volatility of results
